spring:
  application:
    name: authen
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Anu@20021214
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 🔹 dev only, production use validate


  mail:
    host: smtp.gmail.com
    port: 587
    username: "anuradhawork123@gmail.com"
    password: "umae tfzt zkli wjow"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "Y2hhbGxlbmdlVG9Xcml0ZUZ1bGxQcmVkaWN0YWJsZVNlY3JldEtleQ==" # 32 bytes base64

  cookie:
    secure: false   # 🔹 true for prod
    same-site: Lax  # 🔹 None for prod


